---
script: bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ragel

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.2
  - jruby

matrix:
  allow_failures:
    # JRuby is allowed to fail until Racc has a pure Java port.
    - rvm: jruby

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    email:
      on_success: change
      on_failure: change

cache: bundler

branches:
  only:
    - master
